<?php

namespace CalcBundle\Repository;

/**
 * BuyersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyersRepository extends \Doctrine\ORM\EntityRepository
{
}
